### ISSUE TITLE
Update the OM Lspec to reflect the changes implemented in v0.5 of the OML server.

### ISSUE THREAD

**Issue by melaasar** [opencaesar/oml-spec#8]
## User Story
As an OML author, I want to see the OML spec updated to reflect the changes made to the abstract syntax in the v0.5 of the OML server, so I can update my OML models based on it.

## Acceptance Criteria
- [ ] The Abstract Syntax chapter of the OML spec (https://opencaesar.github.io/oml-spec/) updated to reflect the changes made in v0.5 of the OML server.

**Comment by dwagmuse** [comment]
Shouldn't you update and review the spec first?

**Comment by melaasar** [comment]
Done!
